services:
  frontend:
    container_name: kapitelshelf-frontend
    image: thomasmiller01/kapitelshelf-frontend:test
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      VITE_KAPITELSHELF_API: http://localhost:5261
    ports:
      - "5173:5173"

  api:
    container_name: kapitelshelf-api
    image: thomasmiller01/kapitelshelf-api:test
    restart: unless-stopped
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      KapitelShelf__Database__Host: host.docker.internal:5432
      KapitelShelf__Database__Username: kapitelshelf
      KapitelShelf__Database__Password: kapitelshelf
    ports:
      - "5261:5261"
    volumes:
      - kapitelshelf_data:/var/lib/kapitelshelf/data

  migrator:
    container_name: kapitelshelf-migrator
    image: thomasmiller01/kapitelshelf-migrator:test
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KapitelShelf__Database__Host: host.docker.internal:5432
      KapitelShelf__Database__Username: kapitelshelf
      KapitelShelf__Database__Password: kapitelshelf

  # ----- database -----
  postgres:
    image: postgres:16.8
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: kapitelshelf
      POSTGRES_PASSWORD: kapitelshelf
      POSTGRES_DB: kapitelshelf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  kapitelshelf_data:
  postgres_data: