// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class AddUserIdToSeriesWatchlistIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SeriesWatchlistItems_SeriesWatchlist_SeriesId",
                table: "SeriesWatchlistItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SeriesWatchlist",
                table: "SeriesWatchlist");

            migrationBuilder.AddColumn<Guid>(
                name: "SeriesWatchlistModelSeriesId",
                table: "SeriesWatchlistItems",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SeriesWatchlistModelUserId",
                table: "SeriesWatchlistItems",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_SeriesWatchlist",
                table: "SeriesWatchlist",
                columns: new[] { "SeriesId", "UserId" });

            migrationBuilder.CreateIndex(
                name: "IX_SeriesWatchlistItems_SeriesWatchlistModelSeriesId_SeriesWat~",
                table: "SeriesWatchlistItems",
                columns: new[] { "SeriesWatchlistModelSeriesId", "SeriesWatchlistModelUserId" });

            migrationBuilder.AddForeignKey(
                name: "FK_SeriesWatchlistItems_SeriesWatchlist_SeriesWatchlistModelSe~",
                table: "SeriesWatchlistItems",
                columns: new[] { "SeriesWatchlistModelSeriesId", "SeriesWatchlistModelUserId" },
                principalTable: "SeriesWatchlist",
                principalColumns: new[] { "SeriesId", "UserId" },
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SeriesWatchlistItems_SeriesWatchlist_SeriesWatchlistModelSe~",
                table: "SeriesWatchlistItems");

            migrationBuilder.DropIndex(
                name: "IX_SeriesWatchlistItems_SeriesWatchlistModelSeriesId_SeriesWat~",
                table: "SeriesWatchlistItems");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SeriesWatchlist",
                table: "SeriesWatchlist");

            migrationBuilder.DropColumn(
                name: "SeriesWatchlistModelSeriesId",
                table: "SeriesWatchlistItems");

            migrationBuilder.DropColumn(
                name: "SeriesWatchlistModelUserId",
                table: "SeriesWatchlistItems");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SeriesWatchlist",
                table: "SeriesWatchlist",
                column: "SeriesId");

            migrationBuilder.AddForeignKey(
                name: "FK_SeriesWatchlistItems_SeriesWatchlist_SeriesId",
                table: "SeriesWatchlistItems",
                column: "SeriesId",
                principalTable: "SeriesWatchlist",
                principalColumn: "SeriesId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
