// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class AddNotificationChildren : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "ParentId",
                table: "Notifications",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Notifications_ParentId",
                table: "Notifications",
                column: "ParentId");

            migrationBuilder.AddForeignKey(
                name: "FK_Notifications_Notifications_ParentId",
                table: "Notifications",
                column: "ParentId",
                principalTable: "Notifications",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Notifications_Notifications_ParentId",
                table: "Notifications");

            migrationBuilder.DropIndex(
                name: "IX_Notifications_ParentId",
                table: "Notifications");

            migrationBuilder.DropColumn(
                name: "ParentId",
                table: "Notifications");
        }
    }
}
