// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class AddCloudStorages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CloudStorages",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Type = table.Column<int>(type: "integer", nullable: false),
                    NeedsReAuthentication = table.Column<bool>(type: "boolean", nullable: false),
                    RCloneConfig = table.Column<string>(type: "text", nullable: false),
                    CloudDirectory = table.Column<string>(type: "text", nullable: true),
                    CloudOwnerEmail = table.Column<string>(type: "text", nullable: false),
                    CloudOwnerName = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CloudStorages", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CloudStorages_Type_CloudOwnerEmail",
                table: "CloudStorages",
                columns: new[] { "Type", "CloudOwnerEmail" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CloudStorages");
        }
    }
}
