// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class UseCloudType : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_CloudConfiguration_Name",
                table: "CloudConfiguration");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "CloudConfiguration");

            migrationBuilder.AddColumn<int>(
                name: "Type",
                table: "CloudConfiguration",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_CloudConfiguration_Type",
                table: "CloudConfiguration",
                column: "Type",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_CloudConfiguration_Type",
                table: "CloudConfiguration");

            migrationBuilder.DropColumn(
                name: "Type",
                table: "CloudConfiguration");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "CloudConfiguration",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "IX_CloudConfiguration_Name",
                table: "CloudConfiguration",
                column: "Name",
                unique: true);
        }
    }
}
