// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class AddBookUserMetadata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Favourite",
                table: "UserBookMetadata");

            migrationBuilder.DropColumn(
                name: "LastReadDate",
                table: "UserBookMetadata");

            migrationBuilder.RenameColumn(
                name: "Comment",
                table: "UserBookMetadata",
                newName: "Notes");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "Notes",
                table: "UserBookMetadata",
                newName: "Comment");

            migrationBuilder.AddColumn<bool>(
                name: "Favourite",
                table: "UserBookMetadata",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastReadDate",
                table: "UserBookMetadata",
                type: "timestamp with time zone",
                nullable: true);
        }
    }
}
