// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KapitelShelf.Data.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class AddVisitedReadingBookIndexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_VisitedBooks_BookId",
                table: "VisitedBooks");

            migrationBuilder.DropIndex(
                name: "IX_ReadingBooks_BookId",
                table: "ReadingBooks");

            migrationBuilder.CreateIndex(
                name: "IX_VisitedBooks_BookId_UserId",
                table: "VisitedBooks",
                columns: new[] { "BookId", "UserId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ReadingBooks_BookId_UserId",
                table: "ReadingBooks",
                columns: new[] { "BookId", "UserId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_VisitedBooks_BookId_UserId",
                table: "VisitedBooks");

            migrationBuilder.DropIndex(
                name: "IX_ReadingBooks_BookId_UserId",
                table: "ReadingBooks");

            migrationBuilder.CreateIndex(
                name: "IX_VisitedBooks_BookId",
                table: "VisitedBooks",
                column: "BookId");

            migrationBuilder.CreateIndex(
                name: "IX_ReadingBooks_BookId",
                table: "ReadingBooks",
                column: "BookId");
        }
    }
}
