apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-api
  {{ include "kapitelshelf.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
          env:
            - name: KapitelShelf__Database__Host
              value: {{ include "postgresql.host" . }}
            - name: KapitelShelf__Database__Username
              value: {{ .Values.postgresql.auth.username }}
            - name: KapitelShelf__Database__Password
              value: {{ .Values.postgresql.auth.password }}
          resources:
            {{ toYaml .Values.api.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-api
  {{ include "kapitelshelf.labels" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
  selector:
    component: api
    release: {{ .Release.Name }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-api
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          {{- range $p := (index .Values.ingress.hosts 0).paths }}
          {{- if eq $p.service "api" }}
          - path: {{ $p.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kapitelshelf.fullname" $ }}-api
                port:
                  number: {{ $p.port }}
          {{- end }}
          {{- end }}
  tls:
    {{ toYaml .Values.ingress.tls | indent 2 }}
{{- end }}
