apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-frontend
  {{ include "kapitelshelf.labels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: frontend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: KAPITELSHELF_API
              value: http://{{ include "kapitelshelf.fullname" . }}-api:{{ .Values.api.service.port }}
          resources:
            {{ toYaml .Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-frontend
  {{ include "kapitelshelf.labels" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    component: frontend
    release: {{ .Release.Name }}
---
{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-frontend
  annotations:
    {{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          {{- range $p := (index .Values.ingress.hosts 0).paths }}
          {{- if eq $p.service "frontend" }}
          - path: {{ $p.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kapitelshelf.fullname" $ }}-frontend
                port:
                  number: {{ $p.port }}
          {{- end }}
          {{- end }}
  tls:
    {{ toYaml .Values.ingress.tls | indent 2 }}
{{- end }}
