apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kapitelshelf.fullname" . }}-migrator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kapitelshelf.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "postgresql.host" . }}; do
                sleep 2
              done
      containers:
        - name: migrator
          image: {{ .Values.migrator.image.repository }}:{{ .Values.migrator.image.tag }}
          imagePullPolicy: {{ .Values.migrator.image.pullPolicy }}
          env:
            - name: KapitelShelf__Database__Host
              value: {{ include "postgresql.host" . }}
            - name: KapitelShelf__Database__Username
              value: {{ .Values.postgresql.auth.username }}
            - name: KapitelShelf__Database__Password
              value: {{ .Values.postgresql.auth.password }}
          resources: {{ toYaml .Values.migrator.resources | nindent 12 }}