apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kapitelshelf.name" . }}-data
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kapitelshelf.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.global.storage.size }}