global:
  deployPostgres: true

frontend:  
  image:
    # -- Docker image repository
    # @section -- Frontend Values
    repository: thomasmiller01/kapitelshelf-frontend
    # -- Docker image tag
    # @section -- Frontend Values
    tag: "0.1.0"
    # -- Docker [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images)
    # @section -- Frontend Values
    pullPolicy: IfNotPresent

  service:
    # -- Frontend port
    # @section -- Frontend Values
    port: 5173

  resources:      
    # -- Sets the frontend container resources limits  
    # @section -- Frontend Values
    limits:
      cpu: 500m
      memory: 512Mi

    # -- Sets the frontend container resources requests 
    # @section -- Frontend Values
    requests:
      cpu: 250m
      memory: 256Mi

api:
  image:
    # -- Docker image repository
    # @section -- Api Values
    repository: thomasmiller01/kapitelshelf-api
    # -- Docker image tag
    # @section -- Api Values
    tag: "0.1.0"
    # -- Docker [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images)
    # @section -- Api Values
    pullPolicy: IfNotPresent

  service:
    # -- Api port
    # @section -- Api Values
    port: 5261

  resources:     
    # -- Sets the api container resources limits
    # @section -- Api Values
    limits:
      cpu: 500m
      memory: 512Mi
      
    # -- Sets the api container resources requests
    # @section -- Api Values
    requests:
      cpu: 250m
      memory: 256Mi

migrator:
  image:
    # -- Docker image repository
    # @section -- Migrator Values
    repository: thomasmiller01/kapitelshelf-migrator
    # -- Docker image tag
    # @section -- Migrator Values
    tag: "0.1.0"
    # -- Docker [imagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images)
    # @section -- Migrator Values
    pullPolicy: IfNotPresent

  resources:
    # -- Sets the migrator container resources limits
    # @section -- Migrator Values
    limits:
      cpu: 500m
      memory: 512Mi
      
    # -- Sets the migrator container resources limits
    # @section -- Migrator Values
    requests:
      cpu: 250m
      memory: 256Mi

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: kapitelshelf.example.com
      paths:
        - path: /api
          service: api
          port: 5261
        - path: /
          service: frontend
          port: 5173
  tls: []

postgresql:  
  auth:
    username: "kapitelshelf"
    password: "kapitelshelf"

    database: kapitelshelf

  primary:
    service:
      port: 5432

      # -- (string) Sets the postgres host, if you're using an external postgres.
      # Will be ignored, if `global.deployPostgres=true`.
      # @section -- PostgreSQL Values
      host:

    persistence:
      size: 50Gi

    # @ignored
    updateStrategy:
      type: RollingUpdate

    resources:
      # -- Sets the postgres container resources limits
      # @section -- PostgreSQL Values
      limits:
        memory: 2Gi

  # @ignored
  readReplicas:
    replicaCount: 0

  # @ignored
  metrics:
    enabled: false