frontend:
  ingress:
    enabled: true
    host: "kapitelshelf.example.com"
    path: /

api:
  ingress:
    enabled: true
    host: "kapitelshelf.example.com"
    path: /api

postgresql:
  auth:
    username: "<POSTGRES_USERNAME>"
    password: "<POSTGRES_PASSWORD>"

  primary:
    persistence:
      size: 50Gi