global:  
  deployPostgresql: false # Disable the PostgreSQL subchart

frontend:
  ingress:
    enabled: true
    host: "kapitelshelf.example.com"
    path: /

api:
  ingress:
    enabled: true
    host: "kapitelshelf.example.com"
    path: /api

postgresql:    
  auth:
    username: "<POSTGRES_USERNAME>"
    password: "<POSTGRES_PASSWORD>"

  primary:
    service:
      # Set the host and port to the external PostgreSQL instance
      host: "<POSTGRES_HOST>" 
      port: 5432

