name: Publish Helm Chart

on:
  workflow_dispatch: {} # allow manual run
  push:
    branches:
      - main
    paths:
      - 'helm/kapitelshelf/CHANGELOG.md' # only run when the Chart version got bumped

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dev dependencies
        run: npm install

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Package Helm Chart
        run: |
          npm run build:helm

      - name: Move artifacts into /helm folder
        run: |
          mkdir -p ./helm/deploy/helm
          mv ./helm/build/* ./helm/deploy/helm/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm/deploy
          keep_files: true

      - name: Extract CHANGELOG for Release
        id: extract_changelog
        working-directory: ./helm/kapitelshelf
        run: |
          # Pull the section under "## vX.Y.Z" up until the next "## "
          sed -n '/^## v'"$VERSION"'/,/^## /{ /^## /d;p }' CHANGELOG.md > release_body.txt

          # Export it as a multiline ENV for use in create-release
          echo 'RELEASE_BODY<<EOF' >> $GITHUB_ENV
          cat release_body.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: helm@v${{ env.VERSION }}
          release_name: "Helm Chart v${{ env.VERSION }}"
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false