name: Publish Migrator Docker Image

on:
  workflow_dispatch: {} # allow manual run
  push:
    branches:
      - main
    paths:
      - 'backend/src/KapitelShelf.Data.Migrations/CHANGELOG.md' # only run when the migrator version got bumped

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract version from package.json
      working-directory: ./backend/src/KapitelShelf.Data.Migrations
      id: version
      run: |
        # grab the first <Version>…</Version> value
        VERSION=$(grep -m1 '<Version>' KapitelShelf.Data.Migrations.csproj \
          | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        # split into major / minor
        MAJOR=${VERSION%%.*}
        echo "MAJOR=$MAJOR" >> $GITHUB_ENV

        MINOR=$(echo "$VERSION" | cut -d. -f2)
        echo "MINOR=$MINOR" >> $GITHUB_ENV

        # combine for x.y tag
        echo "MAJOR_MINOR=$MAJOR.$MINOR" >> $GITHUB_ENV

    - name: Build initial docker image and push
      working-directory: ./backend/src/KapitelShelf.Data.Migrations
      shell: pwsh
      run: |
        ./build.ps1 -repository $DOCKERHUB_REGISTRY -tag latest

    - name: Retag images and push to $DOCKERHUB_REGISTRY
      run: |
        echo "Re-tag and push '$VERSION' to $DOCKERHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$VERSION
        docker push $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$VERSION

        echo "Re-tag and push '$MAJOR_MINOR' to $DOCKERHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR_MINOR
        docker push $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR_MINOR

        echo "Re-tag and push '$MAJOR' to $DOCKERHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR
        docker push $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR

        echo "Push 'latest' to $DOCKERHUB_REGISTRY"
        docker push $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest

    - name: Retag images and push to $GITHUB_REGISTRY
      run: |
        echo "Re-tag and push '$VERSION' to $GITHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$VERSION
        docker push $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$VERSION

        echo "Re-tag and push '$MAJOR_MINOR' to $GITHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR_MINOR
        docker push $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR_MINOR

        echo "Re-tag and push '$MAJOR' to $GITHUB_REGISTRY"
        docker tag $DOCKERHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:latest $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR
        docker push $GITHUB_REGISTRY/thomasmiller01/kapitelshelf-migrator:$MAJOR
