name: Publish API

on:
  workflow_dispatch: {} # allow manual run
  push:
    branches:
      - main
    paths:
      - 'backend/src/KapitelShelf.Api/CHANGELOG.md' # only run when the api version got bumped

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from KapitelShelf.Api.csproj
        working-directory: ./backend/src/KapitelShelf.Api
        id: version
        run: |
          # grab the first <Version>…</Version> value
          VERSION=$(grep -m1 '<Version>' KapitelShelf.Api.csproj \
            | sed -E 's/.*<Version>([^<]+)<\/Version>.*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # split into major / minor
          MAJOR=${VERSION%%.*}
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV

          MINOR=$(echo "$VERSION" | cut -d. -f2)
          echo "MINOR=$MINOR" >> $GITHUB_ENV

          # combine for x.y tag
          echo "MAJOR_MINOR=$MAJOR.$MINOR" >> $GITHUB_ENV

      - name: Build initial docker image and push
        working-directory: ./backend/src/KapitelShelf.Api
        shell: pwsh
        run: |
          ./build.ps1 -repository docker.io -tag latest

      - name: Retag images and push to to docker.io
        run: |
          echo "Re-tag and push '$VERSION' to docker.io"
          docker tag docker.io/thomasmiller01/kapitelshelf-api:latest docker.io/thomasmiller01/kapitelshelf-api:$VERSION
          docker push docker.io/thomasmiller01/kapitelshelf-api:$VERSION

          echo "Re-tag and push '$MAJOR_MINOR' to docker.io"
          docker tag docker.io/thomasmiller01/kapitelshelf-api:latest docker.io/thomasmiller01/kapitelshelf-api:$MAJOR_MINOR
          docker push docker.io/thomasmiller01/kapitelshelf-api:$MAJOR_MINOR

          if [ "$MAJOR" != "0" ]; then
            echo "Re-tag and push '$MAJOR' to docker.io"
            docker tag docker.io/thomasmiller01/kapitelshelf-api:latest docker.io/thomasmiller01/kapitelshelf-api:$MAJOR
            docker push docker.io/thomasmiller01/kapitelshelf-api:$MAJOR
          else
            echo "Skipping major tag (MAJOR=0)"
          fi

          echo "Push 'latest' to docker.io"
          docker push docker.io/thomasmiller01/kapitelshelf-api:latest

      - name: Retag images and push to ghcr.io
        run: |
          echo "Re-tag and push '$VERSION' to ghcr.io"
          docker tag docker.io/thomasmiller01/kapitelshelf-api:latest ghcr.io/thomasmiller01/kapitelshelf-api:$VERSION
          docker push ghcr.io/thomasmiller01/kapitelshelf-api:$VERSION

          echo "Re-tag and push '$MAJOR_MINOR' to ghcr.io"
          docker tag docker.io/thomasmiller01/kapitelshelf-api:latest ghcr.io/thomasmiller01/kapitelshelf-api:$MAJOR_MINOR
          docker push ghcr.io/thomasmiller01/kapitelshelf-api:$MAJOR_MINOR

          if [ "$MAJOR" != "0" ]; then
            echo "Re-tag and push '$MAJOR' to ghcr.io"
            docker tag docker.io/thomasmiller01/kapitelshelf-api:latest ghcr.io/thomasmiller01/kapitelshelf-api:$MAJOR
            docker push ghcr.io/thomasmiller01/kapitelshelf-api:$MAJOR
          else
            echo "Skipping major tag (MAJOR=0)"
          fi

          echo "Push 'latest' to ghcr.io"
          docker tag docker.io/thomasmiller01/kapitelshelf-api:latest ghcr.io/thomasmiller01/kapitelshelf-api:latest
          docker push ghcr.io/thomasmiller01/kapitelshelf-api:latest

      - name: Extract CHANGELOG for Release
        id: extract_changelog
        working-directory: ./backend/src/KapitelShelf.Api
        run: |
          # Pull the section under "## vX.Y.Z" up until the next "## "
          IN_SECTION=0
          while IFS= read -r line
          do
              # If this line is the header for our version, start capturing
              if [[ "$line" =~ ^##\ \[$VERSION\] ]]; then
                  IN_SECTION=1
                  echo "$line"
                  continue
              fi
              # If we reach the next version header, stop capturing
              if [[ "$IN_SECTION" -eq 1 && "$line" =~ ^##\ \[ ]]; then
                  break
              fi
              # Print the line if we're inside the desired version section
              if [[ "$IN_SECTION" -eq 1 ]]; then
                  echo "$line"
              fi
          done < CHANGELOG.md > release_body.txt

          # Export it as a multiline ENV for use in create-release
          echo 'RELEASE_BODY<<EOF' >> $GITHUB_ENV
          cat release_body.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: api@${{ env.VERSION }}
          release_name: "API v${{ env.VERSION }}"
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false