name: Publish Helm Chart

on:
  workflow_dispatch: {} # allow manual run
  push:
    branches:
      - main
    paths:
      - 'helm/kapitelshelf/CHANGELOG.md' # only run when the Chart version got bumped

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dev dependencies
        run: npm install

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Package Helm Chart
        run: |
          npm run build:helm

      - name: Move artifacts into /helm folder
        run: |
          mkdir -p ./helm/deploy/helm
          mv ./helm/build/* ./helm/deploy/helm/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./helm/deploy
          keep_files: true

      - name: Extract version
        id: extract_version
        working-directory: ./helm/kapitelshelf
        run: |
          VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract CHANGELOG for Release
        id: extract_changelog
        working-directory: ./helm/kapitelshelf
        run: |
          # Pull the section under "## vX.Y.Z" up until the next "## "
          awk '
            # when we hit the header for our version, start printing
            $0 ~ "^## '"$VERSION"'[[:space:]]*\\(" { flag=1 }
            # if we see a new header (and have already started), exit
            /^## / && flag && $0 !~ "^## '"$VERSION"'[[:space:]]*\\(" { exit }
            # if flag is set, print the line
            flag { print }
          ' CHANGELOG.md > release_body.txt

          # Export it as a multiline ENV for use in create-release
          echo 'RELEASE_BODY<<EOF' >> $GITHUB_ENV
          cat release_body.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: helm@${{ env.VERSION }}
          release_name: "Helm Chart v${{ env.VERSION }}"
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false